"""empty message

Revision ID: 79530ab7efd2
Revises: 
Create Date: 2021-01-15 06:20:13.344105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79530ab7efd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('code_desc', sa.String(length=100), nullable=True),
    sa.Column('indicator', sa.String(length=100), nullable=True),
    sa.Column('indicator_desc', sa.String(length=100), nullable=True),
    sa.Column('measure', sa.String(length=100), nullable=True),
    sa.Column('measure_desc', sa.String(length=100), nullable=True),
    sa.Column('inequality', sa.String(length=100), nullable=True),
    sa.Column('inequality_desc', sa.String(length=100), nullable=True),
    sa.Column('unit_code', sa.String(length=100), nullable=True),
    sa.Column('unit_code_desc', sa.String(length=100), nullable=True),
    sa.Column('powercode_code', sa.String(length=100), nullable=True),
    sa.Column('powercode_desc', sa.String(length=100), nullable=True),
    sa.Column('reference_period', sa.String(length=100), nullable=True),
    sa.Column('reference_period_desc', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('flag_code', sa.String(length=100), nullable=True),
    sa.Column('flag_code_desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_index')
    # ### end Alembic commands ###
